services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: sukna-app
    container_name: sukna-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - sukna-network
    ports:
      - "9000:9000"
    depends_on:
      - db

  webserver:
    image: nginx:alpine
    container_name: sukna-webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - sukna-network
    depends_on:
      - app

  db:
    image: mysql:5.7
    container_name: sukna-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: sukna
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - sukna-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: sukna-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    networks:
      - sukna-network
networks:
  sukna-network:
    driver: bridge

volumes:
  dbdata:
